# Generated by Django 2.2.6 on 2019-10-26 21:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalMeterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('enf_zone', models.CharField(max_length=21)),
                ('restrict_field', models.CharField(max_length=21)),
                ('type', models.CharField(max_length=21)),
                ('post_num', models.CharField(max_length=11)),
                ('meter_num', models.CharField(max_length=12)),
                ('mech_num', models.CharField(max_length=11)),
                ('coll_zone', models.CharField(max_length=11)),
                ('park_rate', models.CharField(max_length=12)),
                ('a_st', models.CharField(max_length=50)),
                ('b_x', models.CharField(max_length=50)),
                ('c_side', models.CharField(max_length=50)),
                ('d_n', models.CharField(max_length=50)),
                ('e_key', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('handicap', models.IntegerField()),
                ('loading', models.IntegerField()),
                ('motorcycle', models.IntegerField()),
                ('public_field', models.IntegerField()),
                ('onstreet', models.IntegerField()),
                ('struct', models.IntegerField()),
                ('hooded', models.CharField(max_length=50)),
                ('removedate', models.DateField()),
                ('space', models.CharField(max_length=254)),
                ('globalid', models.CharField(max_length=38)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=-1)),
            ],
        ),
    ]
