# Generated by Django 2.2.6 on 2019-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_originalmeterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalmeterdata',
            name='removedate',
            field=models.DateField(null=True),
        ),
    ]
